# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
xcode_workspace: Example/Example.xcworkspace
xcode_scheme: Example
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
- brew update
- brew uninstall xctool && brew install --HEAD xctool
script:
  xctool
  -workspace Example/Example.xcworkspace
  -scheme Example
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
  build 
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO
#env:
#  global:
#    - CODE_SIGN_IDENTITY=""
#    - CODE_SIGNING_REQUIRED=NO

#script:
#- set -o pipefail && xcodebuild test -workspace Example/Example.xcworkspace -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
